### ISSUE TITLE
Error: java.lang.SecurityException

### ISSUE THREAD

**Issue by DL6ER** [parkerlreed/adb-block#4]
I connected an Android 7.0 (Vernee Thor E) phone via USB and enabled USB-Debugging. After blocking two apps, I get the following output:
![screenshot at 2018-01-02 19-36-02](https://user-images.githubusercontent.com/16748619/34495155-2ea94a60-eff4-11e7-8b97-94023520bc50.png)
whereas there is no real output in the terminal
```
$ ./adb-block
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by DL6ER** [comment]
If I manually try what your script seems to be doing, I get
```
$ adb shell pm block com.adups.fota
Error: unknown command 'block'

$ adb shell pm hide com.adups.fota
Error: java.lang.SecurityException: Neither user 2000 nor current process
has android.permission.MANAGE_USERS.
```

However, `disable` does not work, either
```
$ adb shell pm disable com.adups.fota
Error: java.lang.SecurityException: Shell cannot change component state for com.adups.fota/null to 2
```

**Comment by parkerlreed** [comment]
See https://github.com/parkerlreed/adb-block/issues/3

Apparently pm uninstall -k --user current is the new way. Haven't been able to test on my end.

**Comment by DL6ER** [comment]
Oh thanks, closing in favor of #3
